---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chiyu.
--- DateTime: 2026/4/24 15:44
---
--1、参数列表
--1.1优惠卷id
local voucherId =ARGV[1]
--1.2用户id
local userId =ARGV[2]
--2.数据key
--2.1库存key
local stockKey='seckill:stock:' .. voucherId
--2.2订单key
local orderKey='seckill:order:' .. voucherId

if (tonumber(redis.call('get', stockKey)) <= 0) then
   return 1
end
if (redis.call('sismember', orderKey,userId) ==1) then
	return 2
end
redis.call('incrby',stockKey,-1)
redis.call('sadd',orderKey,userId)
return 0